### ISSUE TITLE
For FAT16/32 partition, read each partition’s volume boot record (VBR) and retrieve the  geometric data of the file system

### ISSUE THREAD

**Issue by anthontaylor** [afranc15/mac_conversion#5]
The layout should include:
Reserved area: 
Start sector: 0 
Ending sector: 6 
Size: 7 sectors 
Sectors per cluster: 32 sectors
FAT area: Start sector: 7 
Ending sector: 598
\# of FATs: 2
The size of each FAT: 249 sectors
The first sector of cluster 2: 12234 sectors

**Comment by afranc15** [comment]
Done!
